<?php
/**
 * @var \Stagem\Xpay\Block\Xpay $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<script>
    window.xpay = <?= /* @noEscape */ json_encode($block->getXpayConfig(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;
</script>
<style>
    .label[for="xpay"] {
        display: flex;
        align-items: center;
    }

    .label[for="xpay"] span {
        display: block;
    }

    .label[for="xpay"] .payment-icon {
        margin-left: auto;
        margin-right: 0;
    }
</style>
